name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v1

      - name: Zip looko2 dir
        run: |
          cd /home/runner/work/Home-Assistant-custom-components-Looko2/Home-Assistant-custom-components-Looko2/custom_components/looko2
          zip looko2.zip -r ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/Home-Assistant-custom-components-Looko2/Home-Assistant-custom-components-Looko2/custom_components/looko2/looko2.zip
          asset_name: looko2.zip
          tag: ${{ github.ref }}
          overwrite: true